### ISSUE TITLE
segfault in the runner when the api server isn't running

### ISSUE THREAD

**Issue by lukemarsden** [helixml/helix#142]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x80 pc=0x8190b6]

goroutine 51 [running]:
github.com/helixml/helix/api/pkg/system.NewRetryClient.func2({0xc006c1c8a0?, 0xc0001b1a00?}, 0x0, {0xc004df4ee0?, 0x7ffe56334cd0?})
        /workspace/helix/api/pkg/system/http.go:374 +0x36
github.com/hashicorp/go-retryablehttp.(*Client).Do(0xc0011d9c70, 0xc006f398c0)
        /root/go/pkg/mod/github.com/hashicorp/go-retryablehttp@v0.7.4/client.go:641 +0x66d
github.com/helixml/helix/api/pkg/system.PostRequestBuffer[...]({{0x7ffe56334cb2, 0x5000ec?}, {0x7ffe56334cd0?, 0x104a060?}}, {0xc000a62c20?, 0x1f}, 0x50057a, {0x1098090, 0x10})
        /workspace/helix/api/pkg/system/http.go:329 +0x308
github.com/helixml/helix/api/pkg/system.PostRequest[...]({{0x7ffe56334cb2, 0xc000853f00?}, {0x7ffe56334cd0?, 0x2?}}, {0xc000a62c20?, 0x1f}, 0xc006a7e660)
        /workspace/helix/api/pkg/system/http.go:301 +0x110
github.com/helixml/helix/api/pkg/runner.(*Runner).reportStateLoop(0xc00040a680, {0xc000853f68?, 0xc0004961c0?})
        /workspace/helix/api/pkg/runner/controller.go:292 +0x19e
github.com/helixml/helix/api/pkg/runner.(*Runner).startReportStateLoop(0xc00040a680)
        /workspace/helix/api/pkg/runner/controller.go:277 +0xc9
created by github.com/helixml/helix/api/pkg/runner.(*Runner).StartLooping in goroutine 21
        /workspace/helix/api/pkg/runner/controller.go:210 +0x96
```

see https://mlops-community.slack.com/archives/C0675EX9V2Q/p1706568289753319

**Comment by lukemarsden** [comment]
Kai fixed this
