### ISSUE TITLE
Image file not found error

### ISSUE THREAD

**Issue by binocarlos** [helixml/helix#84]
Nice to meet you. I gave Helix a try, trying to fine tune SDXL on a few images, but it didn't quite work for me. Think it had to do with image processing, perhaps file type issues.
Sharing relevant info for you to diagnose if it helps squash bugs --

```
exit status 1 from cmd - Traceback (most recent call last):
  File "/workspace/cog-sdxl/helix_cog_wrapper.py", line 282, in <module>
    c.run()
  File "/workspace/cog-sdxl/helix_cog_wrapper.py", line 90, in run
    output = train(
  File "/workspace/cog-sdxl/train.py", line 142, in train
    input_dir = preprocess(
  File "/workspace/cog-sdxl/preprocess.py", line 115, in preprocess
    load_and_save_masks_and_captions(
  File "/workspace/cog-sdxl/preprocess.py", line 500, in load_and_save_masks_and_captions
    images = [Image.open(file).convert("RGB") for file in files]
  File "/workspace/cog-sdxl/preprocess.py", line 500, in <listcomp>
    images = [Image.open(file).convert("RGB") for file in files]
  File "/workspace/cog-sdxl/venv/lib/python3.10/site-packages/PIL/Image.py", line 3305, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file './temp_in/IMG_9609.JPG'
```

**Comment by lukemarsden** [comment]
need to handle images with uppercase file extensions. also, when this issue is resolved, get Chris to ping the user who reported it
